import { ICV, IStack } from "@/Interfaces/CV";

export const cvInfo: ICV[] = [
  {
    icon: "/CvIcons/scaleai.jpg",
    name: "Scale AI",
    experienceDescription:
      "As Coder reviewer of AI, I was responsible for ensuring the functionality and quality of the programming code generated by the AI model on the Flamingo Project and Code v Code project. Testing the generated code to ensure it is functional and meets high-quality standards. Evaluating responses generated by the AI model based on a predefined rating scale, correcting as necessary, and providing feedback",
    technologies: "React.js, JavaScript, Python",
    experiencePeriod: "02/2024 - Present",
  },
  {
    icon: "/CvIcons/rod.jpg",
    name: "ROD",
    experienceDescription:
      "Worked on 3+ web applications based on the client's ideas, with attention to user-centered design, performance, security best practices, and SEO. Implemented current technologies, storybooks, process documentation, clean code, and performance improvements",
    technologies: "React.js, Next.js, Node.js, TypeScript, MongoDB, ChakraUI, TailwindCSS, Nest.js",
    experiencePeriod: "07/2023 - Present",
  },
  {
    icon: "/CvIcons/tob.jpg",
    name: "TOB - Group Solutions",
    experienceDescription:
      "Worked on a real estate product based on tokenization [Token Estate]. I focused on the development website by the Frontend, implementing the designs proposed by the UX team, using the latest technologies to enhance functionality and performance, also refactoring and modernizing legacy code for optimal results.",
    technologies: "React.js, Next.js, Node.js, TypeScript, MongoDB, ChakraUI",
    experiencePeriod: "03/2023 - 07/2023",
  },
];

export const stackInfo: IStack[] = [
    {
        name: 'Frontend Development',
        technologies: 'React.js, Next.js, TypeScript, Tailwind, ChakraUI, React Query, Zustand, Redux'
    },
    {
        name: 'Backend Development',
        technologies: 'Node.js, Express.js, Nest.js, Docker'
    },
    {
        name: 'Databases',
        technologies: 'MongoDB, PostreSQL, MySQL'
    },
    {
        name: 'Cloud Services',
        technologies: 'Github, Vercel, Persistent Storage(S3), Cloudinary, Sanity'
    }
];
