import { ICV, IStack } from "@/Interfaces/CV";

export const cvInfo: ICV[] = [
  {
    icon: "/scaleai.jpg",
    name: "Scale AI",
    experienceDescription:
      "As Coder reviewer of AI, I was responsible for ensuring the functionality and quality of the programming code generated by the AI model. Testing the generated code to ensure it is functional and meets high-quality standards. Evaluating responses generated by the AI model based on a predefined rating scale, correcting as necessary, and providing feedback.",
    technologies: "React.js, JavaScript, Python",
    experiencePeriod: "02/2024 - Present",
  },
  {
    icon: "/rod.jpg",
    name: "ROD",
    experienceDescription:
      "Created 3+ web applications based on the client’s ideas, focusing on user experience and interface. Implemented current technologies, storybooks, process documentation, clean code, best practices, and performance improvements. ",
    technologies: "React.js, Next.js, Node.js, TypeScript, MongoDB, ChakraUI, TailwindCSS, Nest.js",
    experiencePeriod: "07/2023 - Present",
  },
  {
    icon: "/tob.jpg",
    name: "TOB - Group Solutions",
    experienceDescription:
      "Development of product and website as Frontend, meticulously implementing designs proposed by the UX team. Utilized the latest frontend technologies to enhance functionality and performance. I used to refactor and fixs legacy code for optimal results.",
    technologies: "React.js, Next.js, Node.js, TypeScript, MongoDB, ChakraUI",
    experiencePeriod: "03/2023 - 07/2023",
  },
];

export const stackInfo: IStack[] = [
    {
        name: 'Frontend Development',
        technologies: 'React.js, Next.js, TypeScript, Tailwind, ChakraUI, React Query, Zustand'
    },
    {
        name: 'Backend Development',
        technologies: 'Node.js, Nest.js, Docker, Go'
    },
    {
        name: 'Databases',
        technologies: 'MySQL, MongoDB, PostreSQL'
    },
    {
        name: 'Cloud Services',
        technologies: 'Github, Vercel, Persistent Storage(S3), Cloudinary, Sanity'
    }
];
